Controllers/AssuranceClientController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BanqueTardi.Controllers
{
    public class AssuranceClientController : Controller
    {
        // GET: AssuranceClientController
        public ActionResult Index()
        {
            return View();
        }

        // GET: AssuranceClientController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AssuranceClientController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AssuranceClientController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AssuranceClientController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AssuranceClientController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AssuranceClientController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AssuranceClientController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/AssuranceClientsController.cs
using Assurance.ApplicationCore.Entites;
using BanqueTardi.ContexteDb;
using BanqueTardi.DTO;
using BanqueTardi.Interfaces;
using BanqueTardi.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BanqueTardi.Controllers
{
    public class AssuranceClientsController : Controller
    {
        private readonly IAssuranceClientServices _assuranceClientServices;
        private readonly BanqueTardiContexte _context;
        public AssuranceClientsController(IAssuranceClientServices assuranceClientServices, BanqueTardiContexte contexte)
        {
            _assuranceClientServices = assuranceClientServices;
            _context = contexte;
        }
        // GET: AssuranceClientsController
        public async Task<ActionResult> Index()
        {
            return View(await _assuranceClientServices.ObtenirTout());
        }

        // GET: AssuranceClientsController/Details/5
        public async Task<ActionResult> Details(string id)
        {
            return View(await _assuranceClientServices.Obtenir(id));
        }

        // GET: AssuranceClientsController/Create
        public ActionResult Create()
        {
            ListeDesClients();
            return View();
        }

        // POST: AssuranceClientsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AssuranceTardiBodyDTO collection)
        {
            
            AssuranceTardi assurance = new AssuranceTardi()
            {
                ClientID = collection.ClientID,
                NomClient = _context.Clients.First(cl=> cl.ClientID == collection.ClientID).NomClient,
                PrenomClient = _context.Clients.First(cl => cl.ClientID == collection.ClientID).PrenomClient,
                DateDeNaissance = _context.Clients.Where(c => c.ClientID == collection.ClientID).Single().DateNaissance,
                CodePartenaire = "TARDI1010",
                CodeRabais= CodeRabais.PRI,
                Solde = collection.Solde,
                Sexe= collection.Sexe,
                EstDiabetique = collection.EstDiabetique,
                EstFumeur = collection.EstFumeur,
                EstHypertendu = collection.EstHypertendu,
                PratiqueActivitePhysique = collection.PratiqueActivitePhysique,
            };

         
                if(ModelState.IsValid)
                {
                    await _assuranceClientServices.Ajouter(assurance);
                    return RedirectToAction(nameof(Index));
                }
                
           
                return View(collection);
            
        }
        [HttpGet]
        // GET: AssuranceClientsController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            ListeDesClients();
            ViewBag.Id = id;
            var assuranceTardi = await _assuranceClientServices.Obtenir(id);
            AssuranceTardiBodyDTO assuranceTardiBodyDTO = new AssuranceTardiBodyDTO()
            { 
               ClientID =  assuranceTardi.ClientID,
               Solde = assuranceTardi.Solde,
               Sexe = assuranceTardi.Sexe,
               EstDiabetique = assuranceTardi.EstDiabetique,
               EstFumeur = assuranceTardi.EstFumeur,
               EstHypertendu = assuranceTardi.EstHypertendu
            };
            return View(assuranceTardiBodyDTO);
        }

        // POST: AssuranceClientsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, AssuranceTardiBodyDTO collection)
        {
            
            AssuranceTardi assurance = new AssuranceTardi()
            {
                ID = id,
                ClientID = collection.ClientID,
                NomClient = _context.Clients.First(cl => cl.ClientID == collection.ClientID).NomClient,
                PrenomClient = _context.Clients.First(cl => cl.ClientID == collection.ClientID).PrenomClient,
                DateDeNaissance = _context.Clients.Where(c => c.ClientID == collection.ClientID).Single().DateNaissance,
                CodePartenaire = "TARDI1010",
                CodeRabais = CodeRabais.PRI,
                Solde = collection.Solde,
                Sexe = collection.Sexe,
                EstDiabetique = collection.EstDiabetique,
                EstFumeur = collection.EstFumeur,
                EstHypertendu = collection.EstHypertendu,
                PratiqueActivitePhysique = collection.PratiqueActivitePhysique,
               
            };
            if (ModelState.IsValid)
            {
                await _assuranceClientServices.Modifier(assurance);
                return RedirectToAction(nameof(Index));
            }
           
                return View(collection);
           
        }

        [HttpGet]
        // GET: AssuranceClientsController/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
              await _assuranceClientServices.Supprimer(id);
            return RedirectToAction(nameof(Index));
        }

        
        
        [HttpGet]
        public async Task<ActionResult> Confirmer(string id)
        {
            await _assuranceClientServices.Confirmer(id);
            return RedirectToAction(nameof(Index));
        }

        private void ListeDesClients(object? selectedValue = null)
        {
            ViewData["Client"] = new SelectList((_context.Clients), "ClientID", "FullName", selectedValue);
        }


    }
}

Views/AssuranceClients/Create.cshtml
@model BanqueTardi.DTO.AssuranceTardiBodyDTO



@{
    ViewData["Title"] = "Create";
}

<h1>Souscription</h1>


<h4>Client</h4>


<div class="row">
    <div class="col-md-4">
        <form asp-controller="AssuranceClients" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
            <div class="form-group">
                <label  class="control-label">Client</label>
                <select asp-for="ClientID" class="form-select" asp-items= "ViewBag.Client" aria-label="Default select example">
                    <option value="">-- Selectionner un client --</option>
                </select>
                @* <span asp-validation-for="FullName" class="text-danger"></span> *@ 
            </div>
            <div class="form-group">
                <label asp-for="Solde" class="control-label"></label>
                <input asp-for="Solde" class="form-control" />
                <span asp-validation-for="Solde" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexe" class="control-label"></label>
                <select class="form-select" aria-label="Default select example">
                    <option selected>Choisir un sexe</option>
                    <option value="1">Masculin</option>
                    <option value="2">Féminin</option>
                </select>
                <span asp-validation-for="Sexe" class="text-danger"></span> 
            </div>
            
            <div>
                <label>Est fumeur?</label>
                <input type="checkbox" asp-for="EstFumeur" />
            </div>
            <div>
                <label>Est diabetique?</label>
                <input type="checkbox" asp-for="EstDiabetique" />
            </div>
            <div>
                <label>Est hypertendu?</label>
                <input type="checkbox" asp-for="EstHypertendu" />
            </div>
            <div>
                <label>Pratique une activité physique?</label>
                <input type="checkbox" asp-for="PratiqueActivitePhysique" />
            </div>
            
            
       

            <div class="form-group">
                <input type="submit" value="Enregister" class="btn btn-primary" style="margin-right:50px"/>
                <a asp-action="Index" asp-controller="AssuranceClients">Liste des contrats</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/AssuranceClients/Edit.cshtml
@model BanqueTardi.DTO.AssuranceTardiBodyDTO



@{
    ViewData["Title"] = "Edit";
}

<h1>Modification</h1>


<h4>Client</h4>


<div class="row">
    <div class="col-md-4">
        <form asp-controller="AssuranceClients" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input name="id" value="@ViewBag.Id" type="hidden" />
           
            <div class="form-group">
                <label class="control-label">Client</label>
                <select asp-for="ClientID" class="form-select" asp-items="ViewBag.Client" aria-label="Default select example">
                    <option value="">-- Selectionner un client --</option>
                </select>
                 @* <span asp-validation-for="FullName" class="text-danger"></span> *@ 
            </div> 
            <div class="form-group">
                <label asp-for="Solde" class="control-label"></label>
                <input asp-for="Solde" class="form-control" />
                <span asp-validation-for="Solde" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexe" class="control-label"></label>
                <select class="form-select" aria-label="Default select example">
                    <option selected>Choisir un sexe</option>
                    <option value="1">Masculin</option>
                    <option value="2">Féminin</option>
                </select>
                <span asp-validation-for="Sexe" class="text-danger"></span>
            </div>

            <div>
                <label>Est fumeur?</label>
                <input type="checkbox" asp-for="EstFumeur" />
            </div>
            <div>
                <label>Est diabetique?</label>
                <input type="checkbox" asp-for="EstDiabetique" />
            </div>
            <div>
                <label>Est hypertendu?</label>
                <input type="checkbox" asp-for="EstHypertendu" />
            </div>
            <div>
                <label>Pratique une activité physique?</label>
                <input type="checkbox" asp-for="PratiqueActivitePhysique" />
            </div>




            <div class="form-group">
                <input type="submit" value="Enregister" class="btn btn-primary" style="margin-right:50px" />
                <a asp-action="Index" asp-controller="AssuranceClients">Liste des contrats</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/AssuranceClients/Index.cshtml
@model IEnumerable<BanqueTardi.DTO.AssuranceTardiDTO>
<p>
    <a asp-controller="AssuranceClients" asp-action="Create">Nouveau contrat</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NomClient)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrenomClient)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Montant)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Prime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Statut)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NomClient)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrenomClient)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Montant)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Statut)
                </td>
                @if (!item.Statut)
                {
                    <td>
                        <a asp-controller="AssuranceClients" asp-action="Edit" asp-route-id="@item.ID">Modifier</a>
                        <a asp-controller="AssuranceClients" asp-action="Delete" asp-route-id="@item.ID">Supprimer</a>
                        <a asp-controller="AssuranceClients" asp-action="Confirmer" asp-route-id="@item.ID">Confirmer</a>

                    </td>
                }
                
            </tr>
        }
    </tbody>
</table>