Models/Client.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BanqueTardi.Models
{
    public class Client
    {
        [DisplayName("Code")]
        public string ClientID { get; set; }

        [MaxLength(150)]
        [DisplayName("Nom")]
        public string NomClient { get; set; }

        [MaxLength(150)]
        [DisplayName("Prénom")]
        public string PrenomClient { get; set; }

        [DataType(DataType.Date)]
        [DisplayName("Date de naissance")]
        public DateTime DateNaissance { get; set; }
        [MaxLength(250)]
        public string Adresse { get; set; }
        [RegularExpression(@"^[A-Za-z]\d[A-Za-z][ -]?\d[A-Za-z]\d$", ErrorMessage = "Le code postal est invalide.")]
        [DisplayName("Code postal")]
        public string CodePostal { get; set; }
        public int NbDecouverts { get; set; }
        [RegularExpression(@"^\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}$", ErrorMessage = "Le Numéro de téléphone n'est pas valide.")]
        public string Telephone { get; set; }
        [DisplayName("Nom parent")]
        public string? NomParent { get; set; }
        [DisplayName("Telephone parent")]
        [RegularExpression(@"^\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}$", ErrorMessage ="Le Numéro de téléphone n'est pas valide.")]
        public string? TelephoneParent { get; set; }
        public string FullName 
        {
            get
            {
                return NomClient + "," + PrenomClient;
            }  
        }


        public virtual ICollection<Compte>? Comptes { get; set; }

    }
}

Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BanqueTardi.ContexteDb;
using BanqueTardi.Models;

namespace BanqueTardi.Controllers
{
    public class ClientsController : Controller
    {
        private readonly BanqueTardiContexte _context;

        public ClientsController(BanqueTardiContexte context)
        {
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clients.ToListAsync());
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.ClientID == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Clients/Create
        public async Task<IActionResult> Create()
        {
            List<Client> clients = await _context.Clients.ToListAsync();
            Client client = new Client();
            if (clients.Count > 0)
            {

                // Recupere le client ayant le plus grand code, en effectuant un tri desc par matricule
                string dernierMatricule = clients.OrderByDescending(cli => cli.ClientID).FirstOrDefault()!.ClientID;

                // Convertir le code à 8 chiffre du code du client ayant le plus grand matricule
                int dernierCode = int.Parse(dernierMatricule.Substring(3));

                // Generation de l'identifiant du client
                client.ClientID = Utils.Utils.GenererIdentifiantClient(dernierCode);
            }
            else
            {
                // Generation de l'identifiant du client
                client.ClientID = Utils.Utils.GenererIdentifiantClient(clients.Count);

            }

            return View(client);
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClientID,NomClient,PrenomClient,DateNaissance,Adresse, CodePostal, Telephone, NomParent, TelephoneParent")] Client client)
        {
            if(client.DateNaissance.Year>= 2010)
            {
                ViewBag.Message = "Impossible d'inscrire un client qui a moins de 15 ans";
                return View(client);
            }

            if (DateTime.Now.Year - client.DateNaissance.Year < 18 &&(client.NomParent == null || client.TelephoneParent == null))
            {
                    ViewBag.MineurMessage = "Précisez le nom d'un de vos parents ainsi que son numero de téléphone";
                    ModelState.AddModelError(nameof(client.NomParent), "Vous devez préciser le nom d'un de vos parents");
                    return View(client); 
            }
            else if (ModelState.IsValid)
            {
               
                _context.Clients.Add(client);
                await _context.SaveChangesAsync();

            }
            //return View(client);
            return RedirectToAction(nameof(Index));
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            if (DateTime.Now.Year - client.DateNaissance.Year < 18)
            {
                ViewBag.MineurMessage = "Mineur";
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("ClientID,NomClient,PrenomClient,DateNaissance,Adresse,CodePostal,NbDecouverts,Telephone,NomParent,TelephoneParent")] Client client)
        {
           

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.ClientID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), "Comptes", new { id = client.ClientID});
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.ClientID == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Client client)
        {
            if (client != null)
            {
                _context.Clients.Remove(client);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<ActionResult> Recherche(string champRecherche)
        {
            List<Client> clients = await _context.Clients.ToListAsync();
            List<Client> listefiltrer = clients.Where(x => (string.IsNullOrEmpty(champRecherche)) ||
            x.NomClient.ToLower().Contains(champRecherche.ToLower())).ToList();
            return View("Index", listefiltrer);
        }

        private bool ClientExists(string id)
        {
            return _context.Clients.Any(e => e.ClientID == id);
        }
    }
}

Controllers/InteretController.cs
using BanqueTardi.ContexteDb;
using BanqueTardi.DTO;
using BanqueTardi.Interfaces;
using BanqueTardi.Models;
using BanqueTardi.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BanqueTardi.Controllers
{
    public class InteretController : Controller
    {
        private readonly IAssuranceInteretServices _assuranceInteretServices;
        private readonly BanqueTardiContexte _contexte;
        public InteretController(IAssuranceInteretServices interetServices, BanqueTardiContexte contexte)
        {
            _assuranceInteretServices = interetServices;
            _contexte = contexte;
        }
        // GET: InteretController
        public ActionResult Index()
        {
            return View();
        }

        // GET: InteretController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: InteretController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InteretController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InteretController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: InteretController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InteretController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: InteretController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<ActionResult> Envoyer()
        {
            List<Client> listeClients = _contexte.Clients.ToList();
            List<InteretRequestDTO> listeObjetInteretDTODuClient = new List<InteretRequestDTO>();
            foreach (Client client in listeClients)
            {
                var Donnee = DonneeGeneraleClient(client.ClientID);
                foreach (Compte compte in Donnee.Comptes)
                {
                    if(compte.TypeCompte!= Comptetype.Cheque)
                    {
                        InteretRequestDTO interetCompteDTO = new InteretRequestDTO()
                        {
                            ClientID = client.ClientID,
                            Montant = compte.Solde,
                            DateFin = DateTime.Now,
                            DateDebutCalcul = (compte.Operations.Any(op => op.Libelle == "Intêret")) ? compte.Operations.OrderByDescending(o => o.DateTransaction).First(op => op.Libelle == "Intêret").DateTransaction : compte.Operations.First().DateTransaction,
                            TauxInteret = compte.TauxInteret,
                            CompteType = compte.TypeCompte
                        };
                        listeObjetInteretDTODuClient.Add(interetCompteDTO);
                    }
                    else if(compte.Solde<0)
                    {
                        InteretRequestDTO interetCompteDTO = new InteretRequestDTO()
                        {
                            ClientID = client.ClientID,
                            Montant = compte.Solde,
                            DateFin = DateTime.Now,
                            DateDebutCalcul = (compte.Operations.Any(op => op.Libelle == "Intêret")) ? compte.Operations.OrderByDescending(o => o.DateTransaction).First(op => op.Libelle == "Intéret").DateTransaction : compte.Operations.First().DateTransaction,
                            TauxInteret = compte.TauxInteret,
                        };
                        listeObjetInteretDTODuClient.Add(interetCompteDTO);
                    }    
                }
            }
            IEnumerable<InteretResponseDTO> lesInteretCalcule = await _assuranceInteretServices.Ajouter(listeObjetInteretDTODuClient);
            List<Compte> listeCompteMAJ = new List<Compte>();
            foreach(InteretResponseDTO reponse  in lesInteretCalcule)
            {
              Compte compteMAJ = _contexte.Compte.First(c => c.TypeCompte == reponse.CompteType && c.ClientID == reponse.ClientID);
                compteMAJ.Solde += reponse.Interet;
                Operation operation = new Operation { 
                    CompteID = compteMAJ.CompteID,
                    Libelle = "Intêret",
                    Montant= reponse.Interet,
                    TypeOperation = CreditDebit.credit
                };
                _contexte.Add(operation);
                listeCompteMAJ.Add(compteMAJ);
            }
            foreach(Compte compte1 in listeCompteMAJ)
            {
                _contexte.Compte.Update(compte1);
            }
            _contexte.SaveChangesAsync();


            return RedirectToAction(nameof(Index), controllerName: "Clients");
        }

        public BanqueIndexData DonneeGeneraleClient(string id)
        {
            BanqueIndexData viewModel = new BanqueIndexData();
            viewModel.Client = _contexte.Clients
                .AsNoTracking()
                .Include(c => c.Comptes)
                !.ThenInclude(cpt => cpt.Operations)
                .Where(c => c.ClientID == id).Single();

            viewModel.Comptes = viewModel.Client.Comptes!.ToList();

            viewModel.Operations = viewModel.Comptes.GroupBy(cpt => cpt.TypeCompte)
                .ToDictionary(
                    grp => grp.Key, // Type de compte
                    grp => grp
                        .SelectMany(cpt => cpt.Operations!)
                        .OrderByDescending(op => op.DateTransaction)
                        .Take(10)
                        .ToList()
                );
            return viewModel;
        }
    }
}

Views/Clients/Create.cshtml
@model BanqueTardi.Models.Client

@{
    ViewData["Title"] = "Create";
}

<h1>Inscrire un nouveau client</h1>


<h4>Client</h4>
@if (ViewBag.Message != null)
{
    <span class="text-danger">@ViewBag.Message</span>
}
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClientID" class="control-label"></label>
                <input asp-for="ClientID" class="form-control" readonly/>
                <span asp-validation-for="ClientID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NomClient" class="control-label"></label>
                <input asp-for="NomClient" class="form-control" />
                <span asp-validation-for="NomClient" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrenomClient" class="control-label"></label>
                <input asp-for="PrenomClient" class="form-control" />
                <span asp-validation-for="PrenomClient" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateNaissance" class="control-label"></label>
                <input asp-for="DateNaissance" class="form-control" />
                <span asp-validation-for="DateNaissance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodePostal" class="control-label"></label>
                <input asp-for="CodePostal" class="form-control" />
                <span asp-validation-for="CodePostal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telephone" class="control-label"></label>
                <input asp-for="Telephone" class="form-control" />
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>
            @if (ViewBag.MineurMessage != null)
            {
                <div class="form-group">
                    <label asp-for="NomParent" class="control-label"></label>
                    <input asp-for="NomParent" class="form-control" />
                    <span asp-validation-for="NomParent" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TelephoneParent" class="control-label"></label>
                    <input asp-for="TelephoneParent" class="form-control" />
                    <span asp-validation-for="TelephoneParent" class="text-danger"></span>
                </div>
            }
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retourner à la liste</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Clients/Delete.cshtml
@model BanqueTardi.Models.Client

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Etes vous sur de vouloir supprimer ce client?</h3>
<div>
    <h4>Client</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomClient)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomClient)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrenomClient)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrenomClient)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateNaissance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateNaissance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodePostal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodePostal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NbDecouverts)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NbDecouverts)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomParent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomParent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TelephoneParent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TelephoneParent)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ClientID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" asp-controller="Comptes" asp-route-id="@Model.ClientID">Retourner à la page précédente</a>
    </form>
</div>

Views/Clients/Details.cshtml
@model BanqueTardi.Models.Client

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Client</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomClient)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomClient)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrenomClient)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrenomClient)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateNaissance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateNaissance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodePostal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodePostal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NbDecouverts)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NbDecouverts)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomParent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomParent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TelephoneParent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TelephoneParent)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ClientID">Modifier</a> |
    <a asp-action="Index" asp-controller="Comptes" asp-route-id="@Model.ClientID">Retourner à la page précédente</a>
</div>

Views/Clients/Edit.cshtml
@model BanqueTardi.Models.Client

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Client</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ClientID" />
            <div class="form-group">
                <label asp-for="NomClient" class="control-label"></label>
                <input asp-for="NomClient" class="form-control" />
                <span asp-validation-for="NomClient" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrenomClient" class="control-label"></label>
                <input asp-for="PrenomClient" class="form-control" />
                <span asp-validation-for="PrenomClient" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateNaissance" class="control-label"></label>
                <input asp-for="DateNaissance" class="form-control" />
                <span asp-validation-for="DateNaissance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodePostal" class="control-label"></label>
                <input asp-for="CodePostal" class="form-control" />
                <span asp-validation-for="CodePostal" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="Telephone" class="control-label"></label>
                <input asp-for="Telephone" class="form-control" />
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>
            @if (ViewBag.MineurMessage != null)
            {
                <div class="form-group">
                    <label asp-for="NomParent" class="control-label"></label>
                    <input asp-for="NomParent" class="form-control" />
                    <span asp-validation-for="NomParent" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TelephoneParent" class="control-label"></label>
                    <input asp-for="TelephoneParent" class="form-control" />
                    <span asp-validation-for="TelephoneParent" class="text-danger"></span>
                </div>
            }
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Comptes" asp-route-id="@Model.ClientID">Retourner à la page précédente</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Clients/Index.cshtml
@model IEnumerable<BanqueTardi.Models.Client>

@{
    ViewData["Title"] = "Index";
}

<h1>Clients</h1>

<p>
    <a style="margin-right:10px" asp-action="Create">Nouveau client</a>
    <a style="margin-right:10px" asp-controller="Interet" asp-action="Index">Calcul des intérêts</a>
    <a asp-controller="AssuranceClients" asp-action="Index">Assurances</a>
</p>
<div style="text-align:right">
    <form method="post" action="@Url.Action("Recherche", "Clients")">
        <input type="text" name="champRecherche" placeholder="Nom ou prénom du client" />
        <button type="submit" class="btn btn-primary">Recherche selon nom</button>
    </form>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClientID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NomClient)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrenomClient)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.Adresse)
            </th>
         
            
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ClientID)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomClient)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrenomClient)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.Adresse)
            </td>
                <td>
                    <a asp-controller="Comptes" asp-action="Index" asp-route-id="@item.ClientID">Gerer</a>

                </td>
        </tr>
}
    </tbody>
</table>