Models/Compte.cs
using BanqueTardi.CustomValidators;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace BanqueTardi.Models
{

    public class Compte
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity), ValidateNever]
        public string CompteID { get; set; }
        [ValidateNever]
        [Display(Name = "Numéro compte")]
        public string NumeroCompte { get; set; }
        [ValidateNever]
        public string ClientID { get; set; }
        [CheckAmountValidation]
        public double Solde { get; set; }
        [ValidateNever]
        public int Identifiant { get; set; }
        [ValidateNever]
        public string Libelle { get; set; }
        [ValidateNever]
        public int TauxInteret { get; set; }
        [ValidateNever]
        public int TauxInteretDecouvert { get; set; }
        public Comptetype TypeCompte { get; set; }

        public virtual ICollection<Operation>? Operations { get; set; }
        public virtual Client? Client { get; set; }
    }
    public enum Comptetype { Cheque, Epargne, Placement }
}

Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BanqueTardi.ContexteDb;
using BanqueTardi.Models;

namespace BanqueTardi.Controllers
{
    public class ClientsController : Controller
    {
        private readonly BanqueTardiContexte _context;

        public ClientsController(BanqueTardiContexte context)
        {
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clients.ToListAsync());
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.ClientID == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Clients/Create
        public async Task<IActionResult> Create()
        {
            List<Client> clients = await _context.Clients.ToListAsync();
            Client client = new Client();
            if (clients.Count > 0)
            {

                // Recupere le client ayant le plus grand code, en effectuant un tri desc par matricule
                string dernierMatricule = clients.OrderByDescending(cli => cli.ClientID).FirstOrDefault()!.ClientID;

                // Convertir le code à 8 chiffre du code du client ayant le plus grand matricule
                int dernierCode = int.Parse(dernierMatricule.Substring(3));

                // Generation de l'identifiant du client
                client.ClientID = Utils.Utils.GenererIdentifiantClient(dernierCode);
            }
            else
            {
                // Generation de l'identifiant du client
                client.ClientID = Utils.Utils.GenererIdentifiantClient(clients.Count);

            }

            return View(client);
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClientID,NomClient,PrenomClient,DateNaissance,Adresse, CodePostal, Telephone, NomParent, TelephoneParent")] Client client)
        {
            if(client.DateNaissance.Year>= 2010)
            {
                ViewBag.Message = "Impossible d'inscrire un client qui a moins de 15 ans";
                return View(client);
            }

            if (DateTime.Now.Year - client.DateNaissance.Year < 18 &&(client.NomParent == null || client.TelephoneParent == null))
            {
                    ViewBag.MineurMessage = "Précisez le nom d'un de vos parents ainsi que son numero de téléphone";
                    ModelState.AddModelError(nameof(client.NomParent), "Vous devez préciser le nom d'un de vos parents");
                    return View(client); 
            }
            else if (ModelState.IsValid)
            {
               
                _context.Clients.Add(client);
                await _context.SaveChangesAsync();

            }
            //return View(client);
            return RedirectToAction(nameof(Index));
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            if (DateTime.Now.Year - client.DateNaissance.Year < 18)
            {
                ViewBag.MineurMessage = "Mineur";
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("ClientID,NomClient,PrenomClient,DateNaissance,Adresse,CodePostal,NbDecouverts,Telephone,NomParent,TelephoneParent")] Client client)
        {
           

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.ClientID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), "Comptes", new { id = client.ClientID});
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.ClientID == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Client client)
        {
            if (client != null)
            {
                _context.Clients.Remove(client);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<ActionResult> Recherche(string champRecherche)
        {
            List<Client> clients = await _context.Clients.ToListAsync();
            List<Client> listefiltrer = clients.Where(x => (string.IsNullOrEmpty(champRecherche)) ||
            x.NomClient.ToLower().Contains(champRecherche.ToLower())).ToList();
            return View("Index", listefiltrer);
        }

        private bool ClientExists(string id)
        {
            return _context.Clients.Any(e => e.ClientID == id);
        }
    }
}

Controllers/OperationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BanqueTardi.ContexteDb;
using BanqueTardi.Models;
using BanqueTardi.DTO;

namespace BanqueTardi.Controllers
{
    public class OperationsController : Controller
    {
        private readonly BanqueTardiContexte _context;

        public OperationsController(BanqueTardiContexte context)
        {
            _context = context;
        }

        // GET: Operations
        public async Task<IActionResult> Index(string id)
        {

            var compte = await _context.Compte
                                        .AsNoTracking()
                                        .Include(c => c.Client)
                                        .FirstOrDefaultAsync(c => c.CompteID == id);

            if (compte == null)
            {
                return NotFound();
            }

            var banqueTardiContexte = _context.Operations.AsNoTracking()
                                            .Include(o => o.Compte)
                                            .Where(o => o.CompteID == id)
                                            .OrderByDescending(o => o.DateTransaction);
            ViewBag.CompteId = compte.NumeroCompte;
            ViewBag.ClientId = compte.ClientID;
            PopulateDropDownOperationType();
            return View(await banqueTardiContexte.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Index([Bind(["TypeOperation", "CompteID"])] OperationBodyRequestDTO operationBody)
        {
            List<Operation>? operation;
            if (operationBody.TypeOperation != null)
            {
                operation = await _context.Operations.AsNoTracking()
                          .Where(o => o.TypeOperation == operationBody.TypeOperation && o.CompteID == operationBody.CompteID)
                          .OrderByDescending(o => o.DateTransaction).ToListAsync();
                ;
            }
            else
            {
                operation = await _context.Operations.AsNoTracking()
                    .Where(o => o.CompteID == operationBody.CompteID)
                .OrderByDescending(o => o.DateTransaction).ToListAsync(); ;
            }


            var compte = await _context.Compte
                            .AsNoTracking()
                            .Include(c => c.Client)
                            .FirstOrDefaultAsync(c => c.CompteID == operationBody.CompteID);

            ViewBag.CompteId = operationBody.CompteID;
            ViewBag.ClientId = compte!.ClientID;
            PopulateDropDownOperationType(operationBody.TypeOperation);

            return View(operation);
        }

        // GET: Operations/Create
        public IActionResult Create(string id)
        {
            if (CompteExists(id))
            {
                var compte = _context.Compte
                .AsNoTracking()
                .Include(c => c.Client)
                .First(c => c.CompteID == id);

                ViewBag.ClientID = compte!.ClientID;
                ViewBag.CompteID = compte!.CompteID;
                ViewBag.NumeroCompte = compte!.NumeroCompte;
                PopulateDropDownOperationType();
                return View();
            }
            return NotFound();
        }

        // POST: Operations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompteID,Libelle,Montant,TypeOperation")] Operation operation)
        {
            // Récupérer le compte associé à l'opération
            var compteMAJ = await _context.Compte.Include(c => c.Client)
                .Where(op => op.CompteID == operation.CompteID).SingleOrDefaultAsync();

            if (compteMAJ == null)
            {
                return NotFound();
            }

            // Mettre à jour le solde du compte
            switch (operation.TypeOperation)
            {
                case CreditDebit.credit:
                    compteMAJ!.Solde += operation.Montant;
                    break;
                case CreditDebit.debit:
                    compteMAJ!.Solde -= operation.Montant;
                    break;
                default:
                    break;
            }

            if (compteMAJ.Solde < 0 && compteMAJ.TypeCompte == Comptetype.Cheque)
            {
                // Ajouter une opération de débit pour le découvert
                var decouvertOperation = new Operation
                {
                    CompteID = compteMAJ.CompteID,
                    Libelle = "Découvert",
                    Montant = 10, // Montant du découvert
                    TypeOperation = CreditDebit.debit
                };

                // Mettre à jour le solde du compte après l'ajout du découvert
                compteMAJ.Solde -= decouvertOperation.Montant;

                // Incrémenter le nombre de découverts pour le client
                compteMAJ.Client!.NbDecouverts++;

                // Ajouter l'opération de découvert au contexte
                _context.Add(decouvertOperation);
            }
            else if(compteMAJ.Solde < 0 && compteMAJ.TypeCompte != Comptetype.Cheque)
            {
                ModelState.AddModelError("Echec", "Solde insuffisant");
            }

            if (ModelState.IsValid)
            {

                _context.Add(operation);
                _context.Update(compteMAJ);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new {id = operation.CompteID} );
            }

            var compte = _context.Compte
                                .AsNoTracking()
                                .Include(c => c.Client)
                                .First(c => c.CompteID == operation.CompteID);

            ViewBag.ClientID = compte!.ClientID;
            ViewData["CompteID"] = compte.CompteID;
            PopulateDropDownOperationType(operation.TypeOperation);

            return View(operation);
        }

        // GET: Operations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var operation = await _context.Operations.FindAsync(id);
            if (operation == null)
            {
                return NotFound();
            }
            ViewData["CompteID"] = new SelectList(_context.Compte, "CompteID", "CompteID", operation.CompteID);
            return View(operation);
        }

        // POST: Operations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OperationID,CompteID,Libelle,Montant,DateTransaction,TypeOperation")] Operation operation)
        {
            if (id != operation.OperationID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(operation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OperationExists(operation.OperationID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompteID"] = new SelectList(_context.Compte, "CompteID", "CompteID", operation.CompteID);
            return View(operation);
        }

        // GET: Operations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var operation = await _context.Operations
                .Include(o => o.Compte)
                .FirstOrDefaultAsync(m => m.OperationID == id);
            if (operation == null)
            {
                return NotFound();
            }

            return View(operation);
        }

        // POST: Operations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var operation = await _context.Operations.FindAsync(id);
            if (operation != null)
            {
                _context.Operations.Remove(operation);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OperationExists(int id)
        {
            return _context.Operations.Any(e => e.OperationID == id);
        }

        private bool CompteExists(string id)
        {
            return _context.Compte.Any(e => e.CompteID == id);
        }

        private void PopulateDropDownOperationType(object? selectedValue = null)
        {
            ViewData["TypeOperation"] = new SelectList(Enum.GetValues(typeof(CreditDebit))
                                    .Cast<CreditDebit>()
                                    .Select(tc => new SelectListItem
                                    { Value = tc.ToString(), Text = tc.ToString() }), "Value", "Text", selectedValue);
        }

    }
}

Views/Comptes/Create.cshtml
@model BanqueTardi.Models.Compte

@{
    ViewData["Title"] = "Create";
}

<h1>Nouveau compte pour @ViewBag.ClientID</h1>

<hr />
<div class="row">
    <div class="col-md-4">

        @if (ViewBag.Message != null)
        {
            <div class="badge badge-danger">
                <span>@ViewBag.Message</span>
            </div>
        }
        <form asp-action="Create">
            <input type="hidden" name="ClientID" value="@ViewBag.ClientID" />
            <div class="form-group">
                <label asp-for="TypeCompte" class="control-label"></label>
                <select asp-for="TypeCompte" asp-items="ViewBag.TypeCompte" class="form-control">
                    <option value="">-- Choisir type de compte --</option>
                </select>
                <span asp-validation-for="TypeCompte" class="text-danger"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Solde" class="control-label">Solde d'ouverture</label>
                <input asp-for="Solde" class="form-control" />
                <span asp-validation-for="Solde" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Enregistrer" class="btn btn-primary" />
                <a asp-action="Index" asp-route-id="@ViewBag.ClientID">Gérer client</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Comptes/Delete.cshtml
@model BanqueTardi.Models.Compte

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Compte</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Solde)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Solde)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Identifiant)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Identifiant)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Libelle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Libelle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TauxInteret)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TauxInteret)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TauxInteretDecouvert)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TauxInteretDecouvert)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeCompte)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeCompte)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Client.ClientID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CompteID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Comptes/Details.cshtml
@model BanqueTardi.Models.Compte

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Compte</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Solde)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Solde)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Identifiant)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Identifiant)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Libelle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Libelle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TauxInteret)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TauxInteret)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TauxInteretDecouvert)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TauxInteretDecouvert)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeCompte)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeCompte)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Client.ClientID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CompteID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Comptes/Edit.cshtml
@model BanqueTardi.Models.Compte

@{
    ViewData["Title"] = "Edit";
}

<h1>Modifier compte @Model.ClientID</h1>

@if (ViewBag.Message != null)
{
    <div class="badge badge-danger">
        <span>@ViewBag.Message</span>
    </div>
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CompteID" />
            <div class="form-group">
                <label asp-for="TypeCompte" class="control-label"></label>
                <select asp-for="TypeCompte" asp-items="ViewBag.TypeCompte" class="form-control">
                    <option value="">-- Choisir type de compte --</option>
                </select>
                <span asp-validation-for="TypeCompte" class="text-danger"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Solde" class="control-label">Solde d'ouverture</label>
                <input asp-for="Solde" class="form-control" />
                <span asp-validation-for="Solde" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Enregistrer" class="btn btn-primary" />
                <a asp-action="Index" asp-route-id="@ViewBag.ClientID">Gérer client</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Comptes/Index.cshtml
@model BanqueTardi.Models.ViewModels.BanqueIndexData

@{
    ViewData["Title"] = "Index";
}

<div>
    <h1 class="h5">Nom <span class="font-weight-bold">@Model.Client.NomClient</span></h1>
    <h1 class="h5">Prénom <span class="font-weight-bold">@Model.Client.PrenomClient</span></h1>
    <h1 class="h5">Code <span class="font-weight-bold">@Model.Client.ClientID</span></h1>
</div>
<div class="mb-3 d-flex justify-content-between">
    <a asp-action="Details" asp-controller="Clients" asp-route-id="@Model.Client.ClientID">Fiche détaillé</a>
    <a asp-action="Edit" asp-controller="Clients" asp-route-id="@Model.Client.ClientID">Modifier</a>
    <a asp-action="Delete" asp-controller="Clients" asp-route-id="@Model.Client.ClientID">Supprimer</a>
    <a asp-action="Create" asp-route-id="@Model.Client.ClientID">Ajouter compte</a>
</div>

@foreach (var compte in Model.Comptes)
{
    <hr />
    <div>
        <div class="d-flex justify-content-between bg-dark text-white p-4">
            <span>Compte: <span class="font-weight-bold">@compte.TypeCompte</span></span>
            <span>No: <span class="font-weight-bold">@compte.NumeroCompte</span></span>
            <a asp-action="Edit" asp-route-id="@compte.CompteID">Modifier</a>
            <a asp-action="Index" asp-controller="Operations" asp-route-id="@compte.CompteID">Historique</a>
            <a asp-action="Create" asp-controller="Operations" asp-route-id="@compte.CompteID">Ajouter Opération</a>
        </div>
        <span class="mb-3 badge badge-success">Les dix(10) dernières opérations</span>
        <table class="table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Montant</th>
                    <th>Description</th>
                </tr>
            </thead>
            @foreach (var operation in Model.Operations[compte.TypeCompte])
            {
                <tbody>
                    <tr>
                        <td>@operation.DateTransaction</td>
                        <td>@operation.Montant</td>
                        <td>@operation.Libelle</td>
                    </tr>
                </tbody>
            }
        </table>
        <div class="d-flex justify-content-end">Solde du compte:<span class="pr-2 font-weight-bold text-success">@compte.Solde$</span></div>
    </div>
}